name: projact_first
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - img/iPhone 17 Pro Max.png
    - img/iphone.png
    - img/PlayStation5.png
    - img/Headphones.png
    - img/HPLaptop15.png
    - img/WiredHeadphones.png
    - img/WirelessHeadphones.png
    - img/iphone17.png
    - img/hand.png
    - img/logott.png
    - img/ssaaa.png